version: '3.2'

services:
  uwsgi:
    image: radicaleinabox-uwsgi
    build:
      context: uwsgi
    volumes:
      - type: volume
        source: data
        target: /usr/local/radicale/data
    restart: unless-stopped
  nginx:
    image: radicaleinabox-nginx
    build:
      context: nginx
    depends_on:
      - uwsgi
    ports: 
      - 5232:80
    restart: unless-stopped

volumes:
  data:
